language: node_js

node_js:
  - "10.14.1"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing SECRET=xxx EXPIRATION=7200 APIBRAVENEWCOIN=https://bravenewcoin-v1.p.rapidapi.com/ APIKEY=7945704872msh114c172508acb06p1e72a2jsn079200953c54
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookstest;" -U postgres
  - npm run migrations-test
